SELECT TABLE_NAME, CONSTRAINT_NAME
FROM information_schema.TABLE_CONSTRAINTS
WHERE CONSTRAINT_SCHEMA = DATABASE()
  AND CONSTRAINT_TYPE = 'FOREIGN KEY';

-- 按查询结果逐条执行，例如：
-- ALTER TABLE `ai0720score` DROP FOREIGN KEY `ai0720score_ibfk_1`;
-- ALTER TABLE `consultant` DROP FOREIGN KEY `consultant_ibfk_1`;
